{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"financials\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "financials",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a79fda9-3685-4d49-9bdc-1d775c7785fb",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c471342-d7f5-41ce-8998-11984f334ec9",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbdf6ed1-8ddb-43b9-beb0-ae517de9d705",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf00cebe-df9a-4b5a-bced-70a81e5a79e2",
            "sourceColumn": "Discount Band",
            "summarizeBy": "none"
          },
          {
            "name": "Units Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c95f9a31-9487-4140-98bc-243d84671be1",
            "sourceColumn": "Units Sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbe993c2-e076-4657-8efa-7fdeb88219cc",
            "sourceColumn": "Manufacturing Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Sale Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f47a352-96a0-4f85-9577-c1a32d834f98",
            "sourceColumn": "Sale Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "04e282cf-b7c0-4061-9446-19b3894b2385",
            "sourceColumn": "Gross Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Discounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ce634c9e-01ad-4c8f-bd7b-f79ac7e3492f",
            "sourceColumn": "Discounts",
            "summarizeBy": "sum"
          },
          {
            "name": " Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "489ef7ef-ef66-485d-a95d-ec3e216d684c",
            "sourceColumn": " Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dabccaf9-e149-4558-a42e-686b9aa4456d",
            "sourceColumn": "COGS",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6268285-309e-4fa1-acce-7f7371b8dc6a",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bbe43f4a-5afa-4bba-ad3e-c95315f12c5e",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2fac3925-80e3-4ae5-8333-e4bf6093778f",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a52d9690-713c-43e0-ba3c-f36c2c0008ac",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eac7d415-2cf4-4208-887c-28a7eb409a40",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c20c54da-96f1-41b8-8b8b-4c6bd07f0e34",
        "partitions": [
          {
            "name": "financials",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                " Source = Excel.Workbook(File.Contents(\"C:\\Program Files\\Microsoft Power BI Desktop\\bin\\SampleData\\Financial Sample.xlsx\"), null, true),",
                "    financials_Table = Source{[Item=\"financials\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(financials_Table,{{\"Segment\", type text}, {\"Country\", type text}, {\"Product\", type text}, {\"Discount Band\", type text}, {\"Units Sold\", type number}, {\"Manufacturing Price\", Int64.Type}, {\"Sale Price\", Int64.Type}, {\"Gross Sales\", type number}, {\"Discounts\", type number}, {\" Sales\", type number}, {\"COGS\", type number}, {\"Profit\", type number}, {\"Date\", type date}, {\"Month Number\", Int64.Type}, {\"Month Name\", type text}, {\"Year\", Int64.Type}})",
                "in",
                " #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}